### ISSUE TITLE
Cannot import name label_map_util 

### ISSUE THREAD

**Issue by Abhirup-K** [ahmetozlu/vehicle_counting_tensorflow#14]
File "D:/ObjectDetect_Project/vehicle_counting_tensorflow/vehicle_detection.py", line 19, in <module>
    from utils import label_map_util

ImportError: cannot import name 'label_map_util'

how can i solve this import error ?

![image](https://user-images.githubusercontent.com/39443812/42281711-06fdff8e-7fc2-11e8-91b8-a9655f7684ea.png)

**Comment by ahmetozlu** [comment]
Which python version do you use?

**Comment by Abhirup-K** [comment]
python 3.6

**Comment by ahmetozlu** [comment]
Please check the installation of TensorFlow Object Detection API: https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md

label_map_util is provided by TensorFlow Object Detection API.
