### ISSUE TITLE
How to Change Label

### ISSUE THREAD

**Issue by AswathGI** [ahmetozlu/vehicle_counting_tensorflow#15]
hi 

I want to detect stop sign alone, which has the id: 13 

So how to change that in util function?

**Comment by ahmetozlu** [comment]
You can detect, count and tracking all the objects or targeted objects using [TensorFlow Object Counting API](https://github.com/ahmetozlu/tensorflow_object_counting_api). 


***Example usage:***
`targeted_objects = "traffic light"`
`object_counting_api.targeted_object_counting(input_video, detection_graph, category_index, is_color_prediction_enabled, targeted_objects)`


And please give a star that [API](https://github.com/ahmetozlu/tensorflow_object_counting_api) if you think that it is useful. Supporting open source community is important, please be aware of this fact.

**Comment by AswathGI** [comment]
Thanks :)
