### ISSUE TITLE
Customising code of roi line

### ISSUE THREAD

**Issue by williamfernando74** [ahmetozlu/vehicle_counting_tensorflow#16]
I want to use this program with another traffic video but can't find the code where the coordinates of roi line is defined. I tried changin the variable in visualization file that was previously set to 200 but it didn't work. Can you please help me with this?

**Comment by ahmetozlu** [comment]
- You should set [ROI_POSITION](https://github.com/ahmetozlu/vehicle_counting_tensorflow/blob/master/utils/visualization_utils.py#L41) variable as considering your case.

- ROI_POSITION variable is used in [predict_speed](https://github.com/ahmetozlu/vehicle_counting_tensorflow/blob/master/utils/visualization_utils.py#L164) method.

- Also you should set this line to draw [ROI_LINE](https://github.com/ahmetozlu/vehicle_counting_tensorflow/blob/master/vehicle_detection_main.py#L153) the position that you want.

I know, the structure does not look crystal clear but developing is on progress and I have been working on developing the architecture, code cleanup and code refactoring.. I will upgrade the project soon with more talented traffic analyzer app also it will have more understandable and lightweight architecture..

**Comment by williamfernando74** [comment]
First of all, kudos for making such an amazing project. Secondly, I want to make it work on the following [video](https://drive.google.com/open?id=184Nwhwi-TnjGG46WtMEMxIuF2d6Bv-qH). So, I changed the ROI_POSITION variable to 630 and the coordinates to draw ROI_LINE to (470, 630), (1170, 630). For some reason, it's still not working. I'd really appreciate if you can help me with this.

**Comment by Viba** [comment]
The predict_speed code has some more coordinates you need to change for it to work with your video, check there.

**Comment by williamfernando74** [comment]
Thank you so much ahmetozlu and Viba. Everything is working fine now. Thanks a lot.

**Comment by Nisarg-Mehta28** [comment]
@williamfernando74 hey can you help me out man i also have the same problem so please help me out it's urgent for me
