### ISSUE TITLE
ROI Line

### ISSUE THREAD

**Issue by AswathGI** [ahmetozlu/vehicle_counting_tensorflow#18]
how to change the position of ROI Line, and now it is horizontal, what should I do.. to make it Vertical for the same video input?

**Comment by OnurBerkayDogan** [comment]
You can find what you are looking for(ROI) between these lines 145-149 in vehicle_detection_main.py.
cv2.line(input_frame,(0,200),(640,200),(0,255,0),5) 
first param is image then location params are second and third.(in parantheses x,y coordinates)
If you want to make it vertical, change   the second and third param.
Additionally fourth param is color and last param is thickness.

**Comment by AswathGI** [comment]
Thank you soo......Much❤️🙏😇

**Comment by AswathGI** [comment]
It worked...😉
Updated one .... cv2.line(input_frame,(400,0),(400,400),(0,0,255),5)

But it didn't count the vehicles that passed over new vertical line. Is there anything else to change in the code?

**Comment by OnurBerkayDogan** [comment]
in visualiziation_utils.py  line 181 if(bottom > ROI_POSITION) in your case you have to change to right or left then speed_prediction.py also you have to change bottom ==> right or left .
It may be good to change ROI_POSITION.
Regards

**Comment by AswathGI** [comment]
I changed, bottom ==> right in both visualiziation_utils.py & speed_prediction.py, but still not counting any. So I'm trying to change ROI_POSITION. 
Anyways... Thank You Sooooooooo Much❤️❤️❤️😇

**Comment by ahmetozlu** [comment]
Also you can check [**this**](https://github.com/ahmetozlu/tensorflow_object_counting_api#cumulative-counting-mode) out! The [TensorFlow Object Counting API](https://github.com/ahmetozlu/tensorflow_object_counting_api) is the base structure that is used on [tensorflow_vehicle_counting](https://github.com/ahmetozlu/vehicle_counting_tensorflow) sample project!
