### ISSUE TITLE
visualization_util Error

### ISSUE THREAD

**Issue by hassaanseeker** [ahmetozlu/vehicle_counting_tensorflow#2]
temp, counter, csv_line = vis_util.visualize_boxes_and_labels_on_image_array(cap.get(1),
                                                                                         image_np,
                                                                                         np.squeeze(boxes),
                                                                                         np.squeeze(classes).astype(np.int32),
                                                                                         np.squeeze(scores),
                                                                                         category_index,
                                                                                         use_normalized_coordinates=True,
                                                                                         line_thickness=4)
This is some part of my code. But i am getting the following error.

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-42-0ee4667eae95> in <module>()
     38                                                                                          category_index,
     39                                                                                          use_normalized_coordinates=True,
---> 40                                                                                          line_thickness=4)
     41             print("-*-GELEN COUNTER: " + str(counter))
     42             temp_counter = temp_counter + counter

~/video-analytics/models/object_detection/utils/visualization_utils.py in visualize_boxes_and_labels_on_image_array(image, boxes, classes, scores, category_index, instance_masks, keypoints, use_normalized_coordinates, max_boxes_to_draw, min_score_thresh, agnostic_mode, line_thickness)
    443       box = tuple(boxes[i].tolist())
    444       if instance_masks is not None:
--> 445         box_to_instance_masks_map[box] = instance_masks[i]
    446       if keypoints is not None:
    447         box_to_keypoints_map[box].extend(keypoints[i])

KeyError: 0

**Comment by ahmetozlu** [comment]
Which python version do you use?

And, could you try to run this [code](https://github.com/tensorflow/models/blob/master/research/object_detection/object_detection_tutorial.ipynb) to validate that you have completed necessary installation to run my project. If you can run that code successfully on your machine then you should be able to run my project too.

**Comment by kalpa-subbaiah** [comment]
Hi hassaanseeker,
       What was the fix you gave for this, I am getting the same error as below 

KeyError Traceback (most recent call last)
in ()
38 category_index,
39 use_normalized_coordinates=True,
---> 40 line_thickness=4)
41 print("-*-GELEN COUNTER: " + str(counter))
42 temp_counter = temp_counter + counter

~/video-analytics/models/object_detection/utils/visualization_utils.py in visualize_boxes_and_labels_on_image_array(image, boxes, classes, scores, category_index, instance_masks, keypoints, use_normalized_coordinates, max_boxes_to_draw, min_score_thresh, agnostic_mode, line_thickness)
443 box = tuple(boxes[i].tolist())
444 if instance_masks is not None:
--> 445 box_to_instance_masks_map[box] = instance_masks[i]
446 if keypoints is not None:
447 box_to_keypoints_map[box].extend(keypoints[i])

KeyError: 0

**Comment by aditiy2009** [comment]
I have the same error and even I followed all the steps still that error exist

**Comment by ChampionTej05** [comment]
The error is due to unmatching of the arguments of the function. Please check the arguments of the function, it expects IMAGE as the first argument. So just remove cap.get(1) to get rid of the error whereas the output is also ambigious. Function return image and @ahmetozlu  is collecting counter, csv_line.
