### ISSUE TITLE
Tensorflow version check throws error

### ISSUE THREAD

**Issue by austin-carnahan** [ahmetozlu/vehicle_counting_tensorflow#24]
Line 38 of vehicle_detection_main.py checks for tf.__version__ < '1.4.0' and throws an error for tensorflow v1.10+

I guess because numerically 1.10.0 is < 1.4.0

**Comment by koenkoppens** [comment]
Trying to setup the vehicle counting project on a NVidea Jetson Nano. 
Tensorflow version currently support is:

tensorflow-estimator (1.13.0)
tensorflow-gpu (1.13.1+nv19.5)

Is there any way I should be able to make this work, or just wait until tensorflow version 1.4 is supported?

**Comment by ChampionTej05** [comment]
@koen81  Yes, it works. Just comment out that line. As suggested by @austin-carnahan , comparison made in the IF condition is not correct hence you will get errors. If you are assured that your TF version is >1.4 , it is good to go
