### ISSUE TITLE
Issue about counting the vehicle

### ISSUE THREAD

**Issue by Akhtar303nu** [ahmetozlu/vehicle_counting_tensorflow#27]
Hi @ahmetozlu this code sometime detect(count) vehicle and sometime it doesn't count the vehicle 
suggest some changes or any link which will help me and if you solve this issue please share the code 
Thanks

**Comment by ahmetozlu** [comment]
Hey,

Success of the detection depends the model that I chosed "MobileNet-SSD" for this sample project! You can work on "**[Transfer Learning](https://medium.com/coinmonks/modelling-transfer-learning-using-tensorflows-object-detection-model-on-mac-692c8609be40)**" or you can train the MobileNet-SSD from scratch to improve detection!

Success of the counting depends the algorithm that uses main parameters are about the ROI locations which can be modified by **[this line](https://github.com/ahmetozlu/vehicle_counting_tensorflow/blob/master/utils/speed_and_direction_prediction_module/speed_prediction.py#L37)** as considering your case specs (for example fps)! Thus, you can improve the accuracy of object counting module.
