### ISSUE TITLE
Vehicle detection problem

### ISSUE THREAD

**Issue by Akhtar303nu** [ahmetozlu/vehicle_counting_tensorflow#28]
Hi guys
we know that this model (ssd_mobilenet_v1_coco_2017_11_17) is general object detection problem  which changes we perform to detect only vehicle like in this project 
Thanks

**Comment by ahmetozlu** [comment]
You can work on "**[Transfer Learning](https://medium.com/coinmonks/modelling-transfer-learning-using-tensorflows-object-detection-model-on-mac-692c8609be40)**" or you can train the MobileNet-SSD from scratch!
