### ISSUE TITLE
not able to run on raspberry pi 3

### ISSUE THREAD

**Issue by anishkumar0657** [ahmetozlu/vehicle_counting_tensorflow#3]
I tried running this program on raspberry pi 3 but was not able to run it.
Can anyone please help me.

**Comment by ahmetozlu** [comment]
Could you share the error or anything about the problem?

Can Raspery PI's CPU be enough to handle matrix operations that TensorFlow performs? I am not sure of that! TensorFlow needs CPU (actually it needs GPU to reach real time performance) to run properly.

**Comment by anishkumar0657** [comment]
Yes raspberry pi's CPU be enough to handle matrix operations so can i run this program on Windows 10 in my laptop.
Do i need to install COCO API?

**Comment by ahmetozlu** [comment]
https://github.com/ahmetozlu/vehicle_counting_tensorflow#installation

**Comment by anishkumar0657** [comment]
I am getting an error when i am trying to Protobuf Compilation on windows 10.
command used: " protoc object_detection/protos/*.proto --python_out=. "
this is the error:
" 'protoc' is not recognized as an internal or external command,
operable program or batch file. "

**Comment by ahmetozlu** [comment]
Can you follow the [installation guide](https://github.com/ahmetozlu/vehicle_counting_tensorflow#installation)?

And, could you try to run this code to validate that you have completed necessary installation to run my project. If you can run that [code](https://github.com/tensorflow/models/blob/master/research/object_detection/object_detection_tutorial.ipynb) successfully on your machine then you should be able to run my project too.

Bonus: 
 - [Dependencies](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md)
 - [About COCO API installation](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md#coco-api-installation)
