### ISSUE TITLE
Installation Steps for Windows

### ISSUE THREAD

**Issue by prakashkborntowin** [ahmetozlu/vehicle_counting_tensorflow#32]
Hi ,
1.I need to run this source code Windows OS.can you please send me the procedure for run this source code to windows 
2.Is it possible open Visual Studio 2015?

**Comment by ahmetozlu** [comment]
1. [**Here** ](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md)is the installation steps.
2. This project developed on python and you can use any python IDE to edit the project source codes and so on.
