### ISSUE TITLE
color

### ISSUE THREAD

**Issue by Hawkes1996** [ahmetozlu/vehicle_counting_tensorflow#36]
How do I cancel the color prediction

**Comment by ChampionTej05** [comment]
You can comment out the line. Lines 307 to 430 contains all the output printing of data. Comment out the lines that you don't need

**Comment by sidharthskumar** [comment]
> You can comment out the line. Lines 307 to 430 contains all the output printing of data. Comment out the lines that you don't need

which file?

**Comment by sidharthskumar** [comment]
predicted_color = ''
in visualization_utils.py @ line #184
