### ISSUE TITLE
what's with color detection

### ISSUE THREAD

**Issue by PT123123** [ahmetozlu/vehicle_counting_tensorflow#41]
there's no color algorithm here,just read result from csv file?

**Comment by ahmetozlu** [comment]
The project contains **[Color Recognition Module](https://github.com/ahmetozlu/vehicle_counting_tensorflow/tree/master/utils/color_recognition_module)** which performs color classifying by K-Nearest Neighbors Machine Learning Classifier which is trained by R, G, B Color Histogram. It can classify White, Black, Red, Green, Blue, Orange, Yellow and Violet.

For more detailed information, see the orginal repo of the [**Color Recognition project**](https://github.com/ahmetozlu/color_recognition).
