### ISSUE TITLE
Not able to run on raspberry pi 3.....i need a model which can count vehicles via picamera

### ISSUE THREAD

**Issue by vinheat** [ahmetozlu/vehicle_counting_tensorflow#44]

**Comment by ahmetozlu** [comment]
In this project, [**TensorFlow trained models**](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md), which requires computational power (GPU) to run properly, have been used so you need to make the model more lightweight or use the lightweight models such as [**SSD Mobilenet**](http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_coco_2018_01_28.tar.gz). However, I highly recommend you to use the more traditional image processing approaches to detect vehicles such as using SVM classifier is trained HOG features ([**a sample project for it**](https://github.com/ahmetozlu/vehicle_counting_hog_svm)). Then implement the speed prediction algorithm, which is used in this project, from scratch and merge it with your HOG+SVM based detector. It would be so much suitable to work on raspberry pi than using this project directly.

**Comment by vineeth2628** [comment]
Thank you for your response... Your help is so important to my project...
Keep helping many folks and stay happy!!
