### ISSUE TITLE
Use webcam instead of video

### ISSUE THREAD

**Issue by aditiy2009** [ahmetozlu/vehicle_counting_tensorflow#45]

**Comment by aditiy2009** [comment]
I tried to modify the code for webcam but it does not work can anyone help me out.

**Comment by ahmetozlu** [comment]
Read webcam frames by using the code part, which is given below, rather than reading frames from video as doing on **[this line](https://github.com/ahmetozlu/vehicle_counting_tensorflow/blob/master/vehicle_detection_main.py#L113)**:
  
    cap = cv2.VideoCapture(0)
    while(1):
        # Take each frame
        _, frame = cap.read()
