### ISSUE TITLE
Setting coordinates for new video

### ISSUE THREAD

**Issue by tech123master** [ahmetozlu/vehicle_counting_tensorflow#46]
Hi. I want to run my own video. What to change and how to change in the code so as to run my own vehicle traffic video. 
Thanks in advance!!

**Comment by ahmetozlu** [comment]
What do you mean? Do you need to run the program on your custom video record to detect vehicles? Could you specify your issue, please? Thus, I can try to help you better! Thanks..

**Comment by tech123master** [comment]
Hi,
Yes. I need to run my custom video record to detect vehicles.

But unfortunately If I use my custom video, the program is not able to detect any vehicles. So what are parameters I should change and how to change it, so that I can run my custom video to detect vehicles

Thanks and Regards
Ani

On 17-Apr-2019 6:20 PM, Ozlu <notifications@github.com> wrote:

What do you mean? Do you need to run the program on your custom video record to detect vehicles? Could you specify your issue, please? Thus, I can try to help you better! Thanks..

**Comment by ahmetozlu** [comment]
You can use [**faster_rcnn_nas**](download.tensorflow.org/models/object_detection/faster_rcnn_nas_coco_2018_01_28.tar.gz) (COCO mAP[^1] = 43) frozen inference graph that is able to detect any kind of vehicles on the videos has taken any kind of angles and lightning conditions.

Moreover, you can train your custom vehicle detection model and can find the details in **[here](https://github.com/ahmetozlu/vehicle_counting_tensorflow/tree/master/custom_vehicle_training)** about it.
