### ISSUE TITLE
vedio very slow 

### ISSUE THREAD

**Issue by blackcode92** [ahmetozlu/vehicle_counting_tensorflow#47]

**Comment by ahmetozlu** [comment]
[**_ssd_mobilenet_coco_v1_** ](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md#coco-trained-models)is the fastest option you can run among **_[TensorFlow models zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md#coco-trained-models)_**. You should use **_[TensorFlow GPU](https://www.tensorflow.org/install/gpu)_** to run the detection model faster.
