### ISSUE TITLE
Slow output on using different model

### ISSUE THREAD

**Issue by sidharthskumar** [ahmetozlu/vehicle_counting_tensorflow#51]
i tried it on faster_rcnn_resnet101_coco_2018_01_28 and faster_rcnn_inception_v2_coco_2018_01_28 but both of them results in slow output and not able to detect speed but the already present model in this project works fine.Please help me @ahmetozlu

**Comment by ahmetozlu** [comment]
"results in slow output" depends:
- **[Speed of  the models](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md#coco-trained-models)** you chose.
- Hardware capabilities: the machine that the model runs on it should have enough powerful GPU.

Also, [**tensorflow should be installed wih the GPU support**](https://www.tensorflow.org/install/gpu) so detection models can work faster.
