### ISSUE TITLE
How to fix a bounding box class tag to  vehicle if prediction is > 85

### ISSUE THREAD

**Issue by sidharthskumar** [ahmetozlu/vehicle_counting_tensorflow#52]
i dont want that particular vehicle bounding box predicted class to change frequently anyone here who can help me with that?

**Comment by ahmetozlu** [comment]
just set the **[min_score_thresh](https://github.com/ahmetozlu/vehicle_counting_tensorflow/blob/master/utils/visualization_utils.py#L419)** parameter 0.85

**Comment by sidharthskumar** [comment]
@ahmetozlu thank you for your time sir.
Respected Sir,
It is not like that i want the bounding box not to change..like once its is predicted with probability >80% i want that bounding box to be fixed on that object with its class and not change at all..like not detect again and again. I tried your way but it keeps fluctuating .

**Comment by ahmetozlu** [comment]
You need to improve your model detection accuracy, you can perform transfer learning or fine tuning for it. Thus, you can improve the detection results. You should not fix the bounding box on any location of image, if you do it then you can not track the vehicles! The reason of fluctuation is the model accuracy which can not provide good enough detection for your case!

**Comment by sidharthskumar** [comment]
Respected Sir, @ahmetozlu 
Okay thank you so much i will do.But there is this file mscoco_label_map.pbtxt .I am a begginer so please tell me the function of this file and how to generate a similar .pbtxt from a tensorflow model type .pb after transfer learning.
Waiting for your reply.Thank you
