### ISSUE TITLE
Cannot Detect Motorcycle

### ISSUE THREAD

**Issue by haiqalma** [ahmetozlu/vehicle_counting_tensorflow#54]
i want to detect and counting motorcycle in my video but always failed to detected it. I tried to using ssd_mobilenet_v1_coco_2017_11_17 dataset but still failed..

can anyone help me? i am sorry because i am beginner.

**Comment by ahmetozlu** [comment]
You can use a more powerful model such as [**faster_rcnn_nas**](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md) or you can perform transfer learning or fine tuning on ssd_mobilenet_v1_coco_2017_11_17 to improve the accuracy of the model so you can detect your custom objects.

**Comment by haiqalma** [comment]
thanks for your answer..

i want to use ssd_mobilenet_v1_coco_2017_11_17 dataset. where i must change the source code? only in vehicle_detection_main.py or in other file ?

thanks before
