### ISSUE TITLE
Not working in video with 1920 x 1080

### ISSUE THREAD

**Issue by rameedev** [ahmetozlu/vehicle_counting_tensorflow#56]
Tried the code with a traffic video of resolution 1920 x 1080. I modified the below code

1) vehicle_counting.py -- changed variable 'roi' to desired.

2) object_counting_api.py -- changed code in lines in 199 and 202 to hardcode the roi values.

Let me know if anything additional is to be done and if you need the video file.

**Comment by ahmetozlu** [comment]
What is the issue? Can you share the screenshot, please?

**Comment by rameedev** [comment]
I am attaching the screenshot and in the screenshot you can see the vehicle count stays 0 even when the cars are crossing the roi line. From object classification stand point it does a fair job of distinguishing car,bus person etc.

![Vehicle_Count](https://user-images.githubusercontent.com/9818433/63243975-bbda7b80-c279-11e9-9068-e5829a4a4b6c.png)

**Comment by rameedev** [comment]
I forgot to mention i am using the repository object counting repo for this -- https://github.com/ahmetozlu/tensorflow_object_counting_api

Also I have uploaded the original video to my drive.

https://drive.google.com/file/d/1Y0KQVYFt_3IbF9ZwHH8wy_FJOO7yDs6J/view?usp=sharing

**Comment by ahmetozlu** [comment]
Please check the 3rd answer in here: https://github.com/ahmetozlu/tensorflow_object_counting_api/issues/12#issuecomment-522239334
