### ISSUE TITLE
Problem with TensorFlow 2.0

### ISSUE THREAD

**Issue by caleffiufsm** [ahmetozlu/vehicle_counting_tensorflow#57]
I am having difficulties with TensorFlow 2.0

module 'tensorflow' has no attribute 'GraphDef'

Can't figure out how to work this problem.

**Comment by mytrjp** [comment]
you should be using a downgraded version , tensorflow<=1.5.0 could solve the problem

**Comment by chekoduadarsh** [comment]
@caleffiufsm 
set this in your code it will work fine
```
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

```
