### ISSUE TITLE
Speed Estimation of multiple vehicles

### ISSUE THREAD

**Issue by GaneshKoushik313** [ahmetozlu/vehicle_counting_tensorflow#6]
Hello Sir
Is this source code estimate speed of multiple vehicles?

Thanks and Regards
Ganesh Koushik

**Comment by ahmetozlu** [comment]
Speed prediction for multi-vehicles is supported except a case that vehicles are not detected by the ROI line at the same time but I will release new version of my project that will cover that case also.
