### ISSUE TITLE
Change in position of ROI line

### ISSUE THREAD

**Issue by shivam9804** [ahmetozlu/vehicle_counting_tensorflow#62]
Hi, I have question if I change the position of ROI line for camera whose resolution is 1280*720 and the co-ordinate of ROI line is this (1280,360). So in order to bring these changes in how many places do I have to make changes ?

**Comment by ahmetozlu** [comment]
[Update the "250"](https://github.com/ahmetozlu/vehicle_counting_tensorflow/blob/master/utils/speed_and_direction_prediction_module/speed_prediction.py#L30) with your case to detect and count the cars, and also [update the ROI drawing part](https://github.com/ahmetozlu/vehicle_counting_tensorflow/blob/master/vehicle_detection_main.py#L160) to visualize the detection on ROI line by making it green when cars are passing.

Actually, this should be parametric but I need to perform code clean up for all of the codes to make the project more readable and more robust. However, I have not enough time to do it, it is in progress :)
