### ISSUE TITLE
Not getting any output

### ISSUE THREAD

**Issue by m0ns7er** [ahmetozlu/vehicle_counting_tensorflow#7]
Code is working fine but not getting any output.

**Comment by Uk397** [comment]
Either the process is extremely slow or it fails to come up with an output. Happened with me as well. The main.py has been running for over an hour and still no output. Can you please help?

**Comment by ahmetozlu** [comment]
It seems that you can not meet the system requirements to handle TensorFlow operations.

Please try to run the project on [suitable system](https://www.nvidia.com/en-us/data-center/gpu-accelerated-applications/tensorflow/).
