### ISSUE TITLE
Where is the right place

### ISSUE THREAD

**Issue by yazeedhasan97** [ahmetozlu/vehicle_counting_tensorflow#71]
Hi boss,
I was tracing and checking over the code, it is really awesome, thanks for your efforts. 

I could modify some parts, like reducing the number of classes, removing the line and boxes, ..., etc. Now I have only the cars detection left with no more additions

I was wondering where is the right place to add or modify the code so I can detect the Cars License Plate within the car's contours

**Comment by ahmetozlu** [comment]
You can develop your codes to recognize license plates in a new python file in [utils folder](https://github.com/ahmetozlu/vehicle_counting_tensorflow/tree/master/utils) and call it inside of [visualization_utils.py](https://github.com/ahmetozlu/vehicle_counting_tensorflow/blob/master/utils/visualization_utils.py).
