### ISSUE TITLE
#Asking

### ISSUE THREAD

**Issue by gulraizramzan** [ahmetozlu/vehicle_counting_tensorflow#76]
Can i run this code on google colab or windows

**Comment by ahmetozlu** [comment]
To be able to run this project on colab, it is needed to customized some parts of the codes. However, it can be run on Windows after the proper installation of the TensorFlow. [Here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf1.md#installation) is the installation guide.  Also, please check [this](https://github.com/ahmetozlu/tensorflow_object_counting_api/issues/37#issuecomment-830567418) about tf versioning.
